### PR TITLE
feat: upgrades to go@1.19, participle@v2.0.0

### PR DESCRIPTION
**Pull request by cludden**
This fixes conflicts between this module and other modules with a dependency on `github.com/alecthomas/participle/v2`.

### CODE REVIEW

**Comment by divarvel** [comment]
Thanks! I've cleared the CI to run

**Comment by cludden** [comment]
Thanks @divarvel, looks like I forgot to update the go version in `test.Dockerfile`, updated and test locally 🙏

**Comment by divarvel** [comment]
the remaining error seems unrelated to your changes, i think it happens on every branch (i'm not familiar with the CI jobs though, so i'm not sure how to fix it)

**Comment by cludden** [comment]
Thanks for taking a look! Let me know if there's anything else I can do!

**Comment by divarvel** [comment]
if you rebase your branch on top of the latest main commit, CI should be green :+1:

**Comment by cludden** [comment]
rebased and included the go version update to GHA config 👍

**Comment by divarvel** [comment]
Thanks!

FYI I'm planning on updating the test suite to add more thorough checks on the conformance suite, and then start working on biscuit V3 support.

Don't hesitate to reach out if you have feedback/ questions

**Review by divarvel — APPROVED** [review]

**Pull request merged**
